### ISSUE TITLE
Use the same port to subscribe to services of different devices.

### ISSUE THREAD

**Issue by Shangwei1024** [COVESA/vsomeip#381]
Two different devices use different ip addresses to provide different services.I want to subscribe to both services using the same port number.I added the following configuration to the json file:
"clients":
[
    {
        "service":"0xc111",
        "instance":"0x0001",
        "unreliable":[30403]
    },
    {
        "service":"0xc112",
        "instance":"0x0001",
        "unreliable":[30403]
    }
]
But it says there is no available port:
2022-08-20 13:38:34.859699 [error] Cannot find free client port for communication to service: 37904 instance: 1 remote_port: 30506 reliable: 0
How can I modify the code so that the same port number can subscribe to different services on different devices.

**Comment by Shangwei1024** [comment]
The current version cannot be implemented.I have achieved it in other ways

**Comment by linuxflavour** [comment]
We also observed similar error like below using reliable ports
Error Json
    {
        "service" : "0x27",
        "instance":"0x1",
        "reliable": ["0"]
    },
Line 146747: 09-22 15:38:43.548  1581  1587 E vsomeip : Cannot find free client port for communication to service: 30 instance: 1 remote_port: 30501 reliable: 1

We were able to avoid error by modifying our json file 
Fixed Json
    {
        "service" : "0x27",
        "instance":"0x1",
        "reliable": ["65535"]
    },
Hope this helps

**Comment by daileyet** [comment]
> The current version cannot be implemented.I have achieved it in other ways

Hello, could you nice to share your solution?

Current I use the version of vsomeip is 3.1.20

Wait for your reply.

**Comment by fcmonteiro** [comment]
Can you retest with the latest version?
We have dropped support to 3.1.x
Thanks

**Comment by daileyet** [comment]
> Can you retest with the latest version? We have dropped support to 3.1.x Thanks

The latest version is still not able to resolve this requirements.

For example configuration as below:
```json
{
"clients":[
{
        "service": "0x0001",
        "instance": "1",
        "unreliable": [
          "30501"
        ]
      },
      {
        "service": "0x002",
        "instance": "1",
        "unreliable": [
          "30501"
        ]
      },
      {
        "reliable_remote_ports": {
          "first": "30500",
          "last": "30500"
        },
        "unreliable_remote_ports": {
          "first": "30500",
          "last": "30500"
        },
        "reliable_client_ports": {
          "first": "30501",
          "last": "30501"
        },
        "unreliable_client_ports": {
          "first": "30501",
          "last": "30501"
        }
      }
]
}
```
In latest code file: `configuration_impl.cpp' is same as v3.1.20, 
```c++
bool configuration_impl::get_client_port(
        service_t _service, instance_t _instance,
        uint16_t _remote_port, bool _reliable,
        std::map<bool, std::set<uint16_t> > &_used_client_ports,
        uint16_t &_client_port) const
```

I add code as below, and it is OK now in v3.1.20
```c++
bool configuration_impl::get_client_port(
        service_t _service, instance_t _instance,
        uint16_t _remote_port, bool _reliable,
        std::map<bool, std::set<uint16_t> > &_used_client_ports,
        uint16_t &_client_port) const {
    bool is_configured(false);
   // ...
    // Configured ports do exist, but they are all in use
    VSOMEIP_ERROR << "Cannot find free client port for communication to service: "
            << _service << " instance: "
            << _instance << " remote_port: "
            << _remote_port << " reliable: "
            << _reliable;

        // FIXME add reuse port support
    uint16_t its_reuse_port(ILLEGAL_PORT);
    if(!_used_client_ports[_reliable].empty()){
        its_reuse_port = *(_used_client_ports[_reliable].begin());
        if (its_reuse_port != ILLEGAL_PORT) {
            _client_port = its_reuse_port;
            VSOMEIP_INFO << "Cannot find free client port, so reuse port configuration for communication to service: "
            << _service << " instance: "
            << _instance << " remote_port: "
            << _remote_port << "client_port:" << _client_port
            << " reliable: " << _reliable;
            return true;
        }
    }
    return false;
}
```

**Comment by fcmonteiro** [comment]
We will have a look

**Comment by anaritarodrigues** [comment]
Hello @daileyet,
We tested with vsomip 3.3.8, last version available, and the issue is not observed.
Which vsomeip version did you use to retest?
